languageCode = "zh-cn"
title = "wd and cc"
baseURL = "https://wdicc.com/"
theme = "hugo-classic"
rsslimit = 30
Paginate = 30

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = 'colorful'
pygmentsUseClassic = false
pygmentsOptions = "linenos=table;"

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = [ "HTML", "RSS", "AMP" ]
page = [ "HTML", "AMP" ]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
  post = "/:filename/"

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 1

[[menu.main]]
    name = "Search"
    url = "https://www.google.com.hk/search?sitesearch=https%3A%2F%2Fwdicc.com%2F&q="
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "/Resume/"
    weight = 2


[[menu.feed]]
    name = "Subscribe"
    url = "/atom.xml"

[params]
  footer = "Theme from [hugo-classic](https://github.com/wd/hugo-classic) fork from [Github](https://github.com/goodroot/hugo-classic)"
  disqus_shortname = "wdicc"
