languageCode = "zh-CN"
title = "wd and cc"
baseURL = "https://wdicc.com/"
theme = "cactus"
rsslimit = 30
pagination.pagerSize = 30

hasCJKLanguage = true
summaryLength = 50

[markup]
  [markup.goldmark.renderer]
    unsafe= true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Search"
url = "https://www.google.com.hk/search?sitesearch=https%3A%2F%2Fwdicc.com%2F&q="
weight = 5

[[menu.main]]
name = "Subscribe"
url = "/atom.xml"
weight = 6

[params]
    subtitle = "--- Happy every day"
    author = "wd"
    logo = "favicon.ico"
    centerTheme = true
    tocInline = true

    mainSection = "posts"
    mainSectionTitle = "Blog"
    postsOnHomePage = 10

    showProjectsList = true
    showAllPostsArchive = false

    css = ['wdicc.css']


    [params.comments]
        enabled = false
        engine = "disqus"

[Services]
[Services.Disqus]
Shortname = "wdicc"

[[params.social]]
name = "Github"
icon = "github"
link = "https://github.com/wd"

[[params.social]]
name = "Twitter"
icon = "twitter"
link = "https://twitter.com/wdicc1413"

# Enable tags.
[taxonomies]
   tag = "tags"

[outputFormats]
    [outputFormats.RSS]
        mediatype = "application/rss"
        baseName = "atom"

preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
  posts = "/:filename/"
