baseurl = "https://wdicc.com"
pagination.pagerSize = 30
theme = 'hugo-bearblog'
rsslimit = 30
summaryLength = 100
hasCJKLanguage = true

title = "wd and cc"
author = "wd"
copyright = "wd © 2025"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

# Sidebar: about/bio
[params]
title = "Happy every day!"
description = "Good good study, day day up!"
favicon= "favicon.ico"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/wd"

[languages]
  [languages.en]
    languageName = 'zh_CN'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 10
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "https://www.google.com.hk/search?sitesearch=https%3A%2F%2Fwdicc.com%2F&q="
    weight = 10
  [[menu.main]]
    identifier = "Subscribe"
    name = "subscribe"
    url = "/atom.xml"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true


  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 1
    endLevel   = 3
    ordered    = true

[outputFormats]
   [outputFormats.RSS]
       mediatype = "application/rss"
       baseName = "atom"

[permalinks]
 posts = "/:filename/"
