+++
date = "2017-03-13T15:19:30+08:00"
title = "My way to keep fit"
tags = ["keepfit", "running", "health"]
+++

* 最简单的减肥方法

前年开始我发现一种比较简单的减肥方法，就是不吃或者少吃晚饭。

这个方法应该不一定对所有人适用。我估计应该只对 BMI(Body Mass Index, 身体质量指数，注意和体脂率不是一个东西)比较高的人有用吧。

我当时 BMI 是 ~98/1.77^2=31.28~ 是属于比较高的，坚持了上面的方法半年之后，大概最瘦的时候是 28，我查了是刚好脱离了肥胖那一档，进入了过重。

我当时所在的公司的上班时间是 10:00 - 19:00，但是经常出现 20:00 以后才从公司走的情况，这样我到家经常是 21:30 或者 22:00 以后。这个时候吃晚饭就太晚了，基本吃饭完了就睡觉了。并且，中午吃饭到这个时候，一般其实已经饿过劲了，那个时间反而没有那么饿了，我就慢慢开始晚上到家之后只吃几个水果。后来慢慢转为不吃东西，或者只吃很少的水果。有时候也会遇到快下班的时候非常饿，这个时候吃点小零食，也就可以了。这种方式减肥，早上和中午基本不控制自己，还是吃的比较好的。

* 自己最近总结的一些健身方法

按照一些理论，在有氧运动一定时间 T 之后，保持一定的心率 HR 继续运动，就会开始消耗脂肪。所谓的 [[https://www.douban.com/note/228079030/][fat burning zone]] (搜索到的，仅供参考)。

对于 T，我看有的说是 20 分钟，有的是 40 分钟。我一般的做法是持续运动 40-50 分钟，不超过一小时。

对于心率，先看下面的公式

#+BEGIN_SRC 
MHR(最大心率) = 220 - age
MHR = 206 - (0.88 x age)
#+END_SRC

上面是最大心率，有多种算法最后应该结果大致有个范围，然后你的减脂的 HR 范围就是 =MHR x (0.7 到 0.8)= 之间。我算出来我的是大概 130-145.

** 节食

如果想要减脂，必须要节食，并且节食之后，我发现不运动体重也会降，直到降到一个平衡点。

节食并不是一下子就从原来中午晚上吃两碗米饭变成只吃一个苹果，这个也是应该有个循序渐进的过程，要不不说身体是否能接受，你自己就坚持不下来。

我的建议是，逐步减少饭量，花 1-2 个月来完成这个过程，一定要给自己定一个什么时间点达到什么目标的方案，否则也会容易被各种诱惑吸引。

节食期间，并非就一直得是清淡饮食，偶尔吃一次大餐也不是不行，但是最好安排在中午，并且吃了之后晚餐一定要减少量。另外注意是「偶尔」，千万别当成常态。

此外，也得注意要按时吃饭，节食本身就很痛苦了，如果不能按时吃饭，比如过了平时饭点再吃，容易吃多，影响节食效果。

我自己的方案，如果今天上午不出门，那就最多喝一杯牛奶做早餐。如果要出门，可以接受大概半个馒头那么多的饮食量。中午也类似，如果不出门就少吃，如果要出门，可以适当比平时多一点点，避免晚上的时候很难熬，或者路上出现低血糖。

我自己控制的结果，是在中午大概3点一顿自助餐的基础上，晚上6点又有不能推掉的酒局的情况下，中午一杯啤酒，晚上一杯红酒，然后第二天重量维持不变。自己感觉还是挺有成就感的，当然也很痛苦。

我目前体重还没有到平台期，还不清楚节食结束之后反弹的情况，但是我自己的打算是平台期或者达到我的目标体重之后，我再继续维持低饮食量一段时间巩固下，把自己的饮食习惯培养好，不再能暴饮暴食的情况下，应该是可以适当放开饮食的。

** 跑步机 vs 椭圆机 vs 动感单车

我自己家里买了一台动感单车，实际实践过之后，用这个有几个缺陷
- 自己练没有动感。在操课房里面教练会带着不停的变换速度，动作，一方面让你觉得没那么无聊，另一方面也是能增加运动量。
- 自己练容易损坏脚踝和膝盖。我自己在家练的时候，基本就是站上面运动 30+ 分钟，脚一直在单车上面脚尖踩着，练完之后脚会疼痛。

我其实挺喜欢在外面跑步，尤其早上，但是因为体重大，好几次都是跑一周之后双腿膝盖会开始疼痛，只好作罢。健身房里面的跑步机冲击比路面跑步小，可以试试看。

最近尝试了跑步机上面跑，坚持 2 周之后，还是出现了一只腿的膝盖疼痛，只好暂停。开始尝试椭圆机。

跑步机上面跑强度比椭圆机肯定强很多，跑步机上面在一个不快的速度下面，我持续跑 15 分钟之后，心率就会达到 150，其实已经有点高了。

跑步机的几个问题
- 容易心率过快
- 不方便听音乐看片子分散注意力
- 不容易不间断坚持跑 30 - 40 分钟
- 膝盖损伤

最后发现椭圆机实在是很不错
- 运动速度慢，不妨碍你看片子听音乐(这个非常重要，否则坚持50分钟很难)
- 速度恒定，也就是心率恒定，你只需要选择一个适合你的减脂的心率的难度就可以了
- 对膝盖冲击比较小

目前正在体验椭圆机中。

** 力量训练

这块目前还比较盲目，只是知道运动完毕之后应该需要进行适当的力量训练，还在摸索。

** 饮食注意

我本身血压高，所以需要低盐。然后减脂的话，一般的讲法是不要吃或者少吃和糖类有关系的食物，比如糖，西瓜这些，以及很容易转换为糖类的食物，比如谷物，大米这些。可以吃肉类（瘦肉或者白肉，比如鸡肉鱼肉）。

我以前基本没做过几个青菜的饭。目前还在摸索中。

不用水煮直接凉拌：黄瓜，西红柿等，莴笋
白水煮了就能接受的：西兰花，菜花
水煮之后过油炒一下加点盐或者酱油的：油菜，蘑菇，小白菜，菠菜
直接过油炒一下加盐或者酱油：芹菜

之前看了一本书，里面讲到几个低盐的方法，就是比如放入火腿肠等本身自带咸味的食材，或者往酸的方向走。对于凉拌菜，可以适当考虑加一点醋，发现还挺不错的。
