---
title: "Resume"
date: 2019-02-12T15:14:28+08:00
tags: ["简历", "resume"]
toc: true
comment: false
---

Already has worked about two decades, worked in many jobs, like SRE, data analyst, DBA, AD delivery system developer, mobile APP and website developer.

** Education

*BeiHang University(AKA Beijing University of Aeronautics and Astronautics or BUAA)*
Graduate in 2002, bachelor degree

** Experience

*BrilliantAero.com (2017 - present)*

Co. founder, tech and product leader. Have builtup the developer team and product team, developed our iOS, Android APP, and the website.

The main developing languages I used are JavaScript, Python, and React Native related technology.

*Qunar.com (2010 - 2016)*

This is the company that I have stayed for the longest time. Mainly doing the following work.

- Data analyst: Build up a team to analyse data for Vacation BU, including log collection, ETL, and displays.
- PostgreSQL DBA: Build up a team to operation and maintenance around one hundred or so PostgreSQL database servers and setup the monitor system for the servers.
- Advertise delivery system: Developed and maintained the CPM and CPC AD delivery system, which page view is about 1 billion per day before I leave.
- Mobile APP and website for Vacation BU: Developed and maintained the vacation section in Qunar APP and the mobile website.

These systems are not only developing by me, we use lots of the popular programming languages including Lua and Python.

*Taobao.com (2009 - 2010)*

Software engineer. Analyzing Data for linezing.com which collecting data/logs from taobao.com use Hadoop and Hive, and some developing work for the user website.

The main developing languages I used are SQL, Java, Shell, HTML, JavaScript.

*Yahoo China (2007 - 2009)*

SRE of data strategy BU, operation and maintenance about 100 servers. During that time, I developed a nagios plugin that can be centralized managed, so we can easily customize our monitoring.

The main developing languages I used are PHP, Perl, Shell.
