---
title: "BJ Chinaunicom Iptv"
date: 2018-03-25T09:21:39+08:00
tags: ["iptv"]
toc: true
---
刚入住现在的房子的时候，只有朝阳有线，当时还没有高清台，机顶盒也很烂。后来大家争取来了歌华有线，好了很多。再之后，我买了华为盒子之后，发现有线电视简直就是情怀了，很少开了，都是在线看视频。尤其后来装了一个 HDP 直播之后，电视节目也可以看了，就更少开有线了。就去把有线盒子给退了。

有段时间岳母在北京住着，离不开有线，HDP 直播很不稳定，节目有时候还打不开什么的，岳母老抱怨。后来想起来，装了北京联通宽带好像会送一个 iptv 的盒子，可以看电视节目。就联系了一下联通，给过来装了一个盒子。

这个盒子只能直接接到光猫的 lan4 口，我的上网的路由器是接在 lan1 口的。盒子虽然支持无线，但是不能直接连我 lan1 口的路由器。这个盒子有自带的遥控器，不好用，并且系统里面会诱导你用点播什么的，不是很爽。前段时间看到一个水木的[[http://www.newsmth.net/bbscon.php?bid=1050&id=757772&ftype=3&num=3435][帖子讲折腾 iptv 的]] ，自己想尝试在任意设备看，就了解了一下。

光猫有的带路由功能，可以直接光猫拨号，以及可以登录后台修改网络结构。有的不带，等于啥功能都没有。IPTV 和通常的上网通道在猫里面是隔离的，不同的 vlan 走不同的网络。所以这也是为什么盒子只能接 lan4，而且这个 lan4 口并不能正常的访问我们的互联网，限制了只能访问那个 iptv 运转需要的网络。而 lan1 可以访问互联网，但是不能访问 iptv 的网络。我家的电视和光猫分别在客厅的两个面对的墙，因为盒子只能直连光猫，那光猫到盒子，盒子到电视都必须是有线，经过客厅线就没法走了。类似下面这样的。

#+BEGIN_SRC 
光猫 lan4 --- 网线 ---> iptv 盒子 --- HDMI ---> 电视
#+END_SRC

后来找到了一个通过电力猫解决的办法。买一对就可以了。类似下面这样。

#+BEGIN_SRC 
光猫 lan4 -- 网线 --> 电力猫1  ........电网..... 电力猫2 ---- 网线 --->  iptv 盒子 ---- HDMI ---> 电视
#+END_SRC

这样基本就可以了。但是那个盒子用起来不爽，所以打算折腾一下。按照那个帖子我试了，我这无法配置光猫，无法控制光猫的 ip 段。这样那个方案似乎就没法用了。后来又找了一些方案，比如[[https://github.com/phorcys/merlin-BJ-Unicomm-IPTV-scripts][这个方案]]可以单路由搞这个事情，但是我发现也有问题，里面需要知道光猫里面的 vlan 划分，我这没法知道，也没法弄了。

后来发现了[[http://www.newsmth.net/bbscon.php?bid=1050&id=760517][另外一个思路]]，解决了我的问题。线路连接思路大概如下。

#+BEGIN_SRC 
光猫 lan1 -- 主路由 WAN
光猫 lan4 -- 辅路由 WAN
辅路由 LAN（任意一个口） --- 主路由 LAN（任意一个口）
#+END_SRC

然后主路由就以前的设置就可以，假设主路由的 LAN 的网段是 192.168.8.x。辅路由需要设置几个地方。

1. 辅路由 LAN 关闭 DHCP。辅路由 LAN 部分 ip 比如设置为 192.168.8.4 (数值可以自己定，不要和其他设备 ip 冲突了)。
2. 辅路由 LAN 里面设置 IPTV 的 Udpxy 端口比如 8012。
3. 辅路由 WAN 设置为通过 DHCP 自动获取 ip。

这个时候，连接到主路由的设备应该就可以通过访问 192.168.8.4 来访问到辅路由的配置界面了。到[[https://opengg.github.io/bj-unicom-iptv/][这里]] udpxy address 输入 192.168.8.4:8012 生成一个 m3u 列表，就可以在连接到主路由的设备里面，通过各种支持的软件里面看了。

如果还想使用 iptv 看，可以在 iptv 的无线设置里面连接辅路由的无线就可以。

这个方案巧妙的使用了路由器自带的交换机功能，把主路由和辅路由放到了一个 LAN 里面。虽然多了一个路由器，但是节省了电力猫，iptv 盒子，电视的一个 HDMI 口。
