---
title: "English Learning"
date: 2020-12-26T17:48:51+08:00
tags: ["English", "skill"]
toc: true
---
我大概算是从 2019 年中开始算是比较多的花了一些时间在英语学习上面，标志是开始认真的去背单词了。在此之前顶多算是一点零散的学习，或者都算不上什么学习。这里多少总结下自己的学习过程。

* 使用 Anki 等符合记忆曲线的工具帮助记忆单词

背单词是学习英语必经之路，宣传不用背单词就可以提升英语能力的都是在耍流氓。而单词学习又是一个很枯燥也基本没有捷径的事情，所以如果真的想提升自己的英语能力，先找一个能让自己坚持下来的单词记忆方式吧。

在使用 Anki 之前也使用过一些别的，例如使用时间比较长的百词斩，界面以及单词卡片做的都很完美，但是对于记忆曲线却并不友好。人们对于单词记忆实际是有区别的，一些单词可能很容易记住，一些可能怎么都记不住。所以记忆过程中是需要分门别类的来设置不同的 review 时间的。Anki 按照记忆曲线会合理安排单词的复习时间，让记住的单词出现的频率降低，记不住的单词出现频率变高。

关于 Anki 我有[[/use-anki-to-leaning-english][另外一篇文章]]有详细一点的说明，这里就不多说了。

* 营造沉浸环境

沉浸环境很重要，语言学习中听说读写都需要多锻炼才能有提升。国内缺少交流环境，尤其对于已经毕业的人，除非在外企工作，或者出国旅行，要不很少会遇到周围都是英语的环境。这个环境需要自己营造，可以尝试的方式比如：
- 把所有自己使用的系统设置为英文。比如我的电脑，手机，电视盒子等都是英文系统。
- 去读英文的文档。开始可以读自己工作相关的，这样会毕竟容易上手，慢慢到各种新闻等。
- 看各种英文的视频，听不懂可以打开字幕看，还可以减速听，暂停反复听。
- 听英文的播客，这个没有字幕可以看，但是可以调慢速度听。对于有声的资料（视频和播客），可以在路上，睡觉前，做家务等的时候听。
- 看英语的新闻。
- 看英语小说。找到合适的小说很重要，可以先从针对青少年的小说看起。实在看不下去就看针对更年轻用户的。

每个人的基础水平不一样，所以上面的这些事情量力而行，一般建议是比如读的文章里面的生词量维持在一个自己可以读下去，又不觉得恶心的比例。毕竟不能坚持下去的话，说什么都没用了。

我手机上面没有抖音微博这些软件，微信也把之前加过的大部分群都退了，同时也关闭了消息提醒。所以我的手机平时非常安静，即使在我想打发时间的时候，也只能打开 Google News，Reddit 等软件看，这也算是另外一种让自己沉浸的方法吧。

* 重复，不断重复

只是浮光掠影的看看听听的话，学习速度会比较慢，因为短期记忆很容易丢失。重复会让这个记忆变的更可靠，其实背单词就是这样的。我曾经一部美剧看过 3-5 遍。看到后面感觉角色说什么都能听懂了。我也看过很多讲英语学习课程，都非常强调重复。现在看看其实以前学校老师让大家背诵课文，也应该是类似的道理。

英语语境里面，很多时候说话会有语调，吞音和连读。这些只有在不断的重复下去体会和把握一句话的重点。开始听的时候可能会觉得每个词都需要听明白，自己才能理解一句话。但是听多了就会发现，其实并不需要这样，结合语境上下文只需要抓住几个词就能明白。这些在大量的练习之后才能找准。

另外还有一个提升的方式就是跟读。找一段自己喜欢的场景对话，模仿里面角色的发音语调等，一样是不断重复多加练习培养自己的口语。

* 坚持

我自己觉得语言学习没有速成的方法，需要持之以恒的训练自己，慢慢提升。例如使用 Anki 记忆单词的时候，如果今天的单词不 review 完毕，这些单词就需要明天 review，然后明天还有明天的单词需要 review，这样就会发现一旦断开一天，接下来就更难了。所以我从来不敢让 Anki 的 review 断开，即使在旅行度假，我每天一早都会先完成功课，或者就是在各种等人，发呆的间隙把 review 完成。

一定要记住，能坚持是最重要的。一旦坚持不下去，即使定了绝美的计划，即使交了很多学费，买了最好的辅助学习工具，也是一场空。所以哪怕今天只是完成了 review 而没有学习新的内容，那也比什么都不做强。
