---
title: "Use Anki to Leaning English"
date: 2019-07-17T11:36:20+08:00
tags: ["anki", "english"]
toc: true
---
Anki 很早以前就听说了，是一款帮助你记忆东西的软件。

教小孩子的时候，一般不是会有一些卡片么，正面是一个字，比如 ~虎~ 背面是一个老虎的图像，这样帮助小孩识字。这种叫做 flashcards 。Anki 提供的就是制作并使用这些 flashcards 来帮助你记忆。

所以广义上面讲，Anki 不止可以用来记忆单词，比如学中文老外可以用来记忆中文，学物理化学的记忆各种公式什么的。正面放需要理解学习的东西，反面放帮助记忆的东西。

Anki 神奇的不是因为可以制作任意的记忆卡片，主要是他的针对所谓的遗忘曲线来学习的套路。所谓遗忘曲线，复杂的逻辑我也没看过，简单的用方便理解的方法来讲，比如我们背单词的时候，刚背玩 1 分钟内，通常是记忆最深刻的，10 分钟后就会有一些模糊了，1 天后可能就会忘记很多今天已经记住的单词了，此后不及时复习的话，你会发现下次再见到和第一次见到没什么区别，完全就是个新的单词一样。这个就是说，随着时间遗忘一个东西的速度会越来越快。

我之前使用百词斩背单词，它把单词都做了的图形化的提示信息，这个非常有助于记忆，我非常喜欢这点。他的工作模式是，每天设定一个目标，比如 20 个单词吧，那今天的任务就是复习昨天的 20 个单词，以及学习今天的 20 个单词，每天都这样一个模式。记得我前面说的遗忘曲线了没，这样的模式你会发现，这两天记忆好的单词，下个月可能就基本不记得啥意思了，和没学一样。而百词斩似乎提供了一些你自己复习的途径，不过我目前没找到合适的方式使用。百词斩对于新的单词，会提供三遍机会学习，第一遍是单词+图片，第二遍是单词+释义，第三遍是根据释义选单词。在每一遍里面，如果你选错了，那就会再出现一遍相同的题目。对于熟悉的单词，还提供了一个 ~斩~ 的选项，斩掉的单词就不会在出现了，你再也没有机会看到这个词了。百词斩还有一个问题是，因为他是选项模式，实际上那些选项也是一个提示，你可以使用排除法来选择答案，所以这些东西有时候会让你觉得你记住这个单词了，但实际上这个单词单独出现的时候不认识。

Anki 的工作模式是这样的，也是每天设定一个目标，比如新学 20 个单词。那今天你需要记忆的单词就包括了今天 ~之前~ 所有需要今天 review 的单词，和今天新的 20 个单词。新的单词没什么好说的，那 review 的单词是怎么构成的呢？当出来一个单词的时候，你根据自己的记忆情况，需要在单词下面的选项选择打算多久之后 review 他，选项按照单词被 review 的次数和你选择的 review 的情况来的，比如新单词的选项是 ~again 1m~, ~good 10m~, ~easy 1d~, 如果你觉得这个词你不太熟悉，你可以从 ~again~ ~good~ 里面选一个，它会持续的在今天的学习里面出现，直到你觉得认识了，那就选 ~easy~ ，那这个词今天就不会出现了，会在明天的 review 里面出现。到了明天，这个词再次出现的时候，选项就变成了 ~again 10m~, ~good 1d~, ~easy 10d~ (具体选项我没记住，这里举个例子)，这个时候，如果发现这个单词忘记了，那就继续 ~again~ ~again~ 的选择直到你觉得记住了，根据你自己的感觉，选择 ~good~ 还是 ~easy~ ，这样会决定他下次是什么时候出现。类似这样，单词你越熟悉，他出现的次数就会越少，而且你也完全不用担心这个单词会不会你只是现在觉得认识了，后面过 1 个月又忘记了怎么办，那放心这些单词会持续出现的。

事实上，Anki 的设计不止这些。在设置里面还有一些因子，这些会影响出现的选项的时间。具体可以看后面提到的视频。使用 Anki 的时候，基本用法如下：
1. 一个新的词，如果已经认识，那选择 ~easy~ 就好了。如果不认识，那根据情况选择 ~1m~ 或者 ~10m~ ，一般看到一个词一点都不认识的时候，多选几次 ~1m~ 加深一下印象，然后选择 ~10m~ 看是不是记住了，然后可以往复的选择 ~1m~ 和 ~10m~ 直到你觉得今天没必要看这个词了，那选择那个 ~1d~ 。
2. 一个需要 review 的词，如果发现没记住，那就选 ~1m~ 让他进入和新词一样的逻辑，直到最后选择 ~1d~ 。
3. 如果需要 review 的词你知道意思，这个时候有几个做法
   1) 这个词确实很简单，那继续 ~easy~ ，让他更少出现。
   2) 这个词有一点难度，是你新学的，但是基本也还能知道怎么回事，那可以选择 ~good~ ，让他适当的没那么少出现。
   3) 对这个词的部分释义不清楚，没记住，那可以酌情选择 ~hard~ ，让他增加出现的机会。

Anki 有一个问题是，随着你学习的新单词越来越多，那需要 review 的单词也越来越多，尤其当你偷懒几天没打开软件，巨大的 review 数量可能会让人崩溃。设置里面可以设置每天 review 的最大数量，默认是 200，如果自己实在不能 review 完可以改一下。我现在设置是 200，每天新词 20 个，看着情况是每天基本是需要处理 60 个词左右。只要持续每天清理就也还好。其实一天那么多时间，大可以利用碎片时间看看，也别担心自己实际没记住但是按了 ~easy~ 的情况，后面还会出现呢，后面出现的时候再好好记也可以。

Anki 还提供了一自定义学习模式，每天 Anki 不是会自动安排任务么，如果一天的任务完成后，还想多学习一些，那 Anki 提供了一个自定义学习模式 Custom Study。点击这个之后，需要你选择想学习什么，可以学习新的单词，也可以复习之前学过的，按照你自己的情况选择就好。选择之后，一些卡片就会添加到那个 Custom Study Session 这个 deck 里面。卡片到这个 deck 之后，如果你学习完毕就会都归还到原来的 deck 里面，也可以点那个 Empty 自己都清空。这个 deck 里面有两个设置比较重要，一个是 Step，我看默认是 1 分钟，这个和前面那个 step 是一个意思。还有一个是 Reschedule cards based on my answers in this deck，如果不选中这个，那一个卡片学习完毕之后，会有两个选项一个是 ~again~ 一个是 ~good~ ，选 good 会结束这个卡片的学习，不会对原来的 deck 里面对这个词的安排有什么影响。如果选中这个选项，那选项会有一个 ~good(n day)~ 这样的，点击之后实际会影响原来 deck 里面对这个词的规划。

[[https://www.youtube.com/watch?v=lz60qTP2Gx0&t=1223s][这里]]有一个对 Anki 的设置和工作模式的详细的解说，有兴趣可以看看。

** 2019.10.9 补充

前几天休假出去玩了一段时间，如何处理 anki 里面的任务是一个大事，我可不想回头因为这几天休假之后 review 太多把这个事情荒废了。还好我感觉我找到了解决 review 太多的方法。

可以通过设置，修改每天的新单词数量为 0 。这样你就只需要 review 历史学过的单词了，因为不会有新词，所以历史的单词 review 也会很快完成，而且还会发现之前积累的一些也慢慢消化了，每天 review 数量会下降。

所以实际上如果不想每天那么大压力，大可以默认设置新单词数量为 0， 再你觉得今天可以学习新单词的时候，通过 custome study 增加今天的新单词数量，这样今天学习之后，明天默认还是没有新单词的。可以灵活的安排你新单词的学习时间。只是 review 旧单词压力会小很多。
