---
title: "Year in Review 2019"
date: 2019-12-18T16:48:58+08:00
tags: ["2019"]
toc: true
---
Here it comes, the end-of-year 2019. The next year will be 2020, it’s more easy to pronounce for foreigners :)

** Works
Finally, I realized that I lack of experience and knowledge to continue run our startup company. When you are the founder of a company yourself, you can’t blame others doing things not well, especially when you didn’t know how to doing it well either. I have to accept the fact that I am not having all the skills that a company needed.

Our APPs and website are entered its stable state last year, and the new goal is that we have to gain more customers, either the skydiving product on Qunar.com, and our APPs.

In fact, we found skydiving is really a minority activities, and it’s easily affected by the weather, wind speed, temperature, and the air traffic control. If someone wants skydiving, he had to make a reservation 2 or 3 days in advance, and also need to leave all day preserved for the skydiving, because the skydiving base usually far from city, he had to take a taxi or bus to arrive the base. He had to wait the air traffic control center to allow the plane to take off, also need to wait the weather, wind are suitable for skydiving. Although it’s only 10 minutes in the sky, sometimes he has to wait for four hours, and there is also a big chance that the base had to cancel the skydiving.

I didn’t know how to attract more customers for skydiving, and we trapped here.

Our customers for general aviation hit a record last year, but we are losing them now, because we didn’t find the way to satisfy them all. Our products didn’t solve the root issue they have. We also didn’t find the way to introduce our APPs to drone pilots, which we thought they were the growth point for us.

Running a company is not just need what you already known, it’s need you to learn much more, because if you didn’t do it or didn’t know how to do it, then no one else will be. You maybe say no one could do all the things, recruit some experts to do it. Yes, you are right, but as a small company, to recruit an expert also need some special abilities. I’m a software engineer before, recruit some expert in a different field is a challenge to me.

I’m finding a job now and trying to find a job work in different countries. I lose an opportunity to work at a global company, due to the poor English spoken language.

** Readings

I have lots of time to read this year. I started reading some English books, hope it’s useful for my English study.
1. 伟大的博弈:华尔街金融帝国的崛起(1653～2011)(珍藏版) (约翰·S·戈登).
2. 1Q84 (村上春树).
3. ﻿1984 ({英} 乔治·奥威尔), Here are the [[/readings/][reviews]] about the above three books.
4. Effective Python：编写高质量 Python 代码的 59 个方法, the review is [[/book-review-of-effective-python/][here]].
5. 软技能, the review is [[/book-review-of-soft-skills/][here]].
6. 编写高质量代码 改善Python程序的91个建议.
7. Untouchable Love, downloaded from [[https://www.obooko.com/free-books-for-teens/untouchable-love][here]], it's free.
8. JoJo的奇妙冒险 1-6, [[https://zh.wikipedia.org/wiki/JoJo%25E7%259A%2584%25E5%25A5%2587%25E5%25A6%2599%25E5%2586%2592%25E9%2599%25A9][here]] is the link from Wikipedia.

** English study
I started to remember English words by using [[/use-anki-to-leaning-english/][Anki]]. It’s really a helpful tool for English study. I have reviewed half of the words of IELTS tests, it’s still a long way to go.

Since 2017, I started watch English movies with English subtitles, I think my English listening skill has improved a lot. I’m trying to improve my spoken English now, I think I should do more English writing practices, it’s will help me think in English instead of think in Chinese and then translate to English.

** Traveling
My wife and I had traveled to many cities this year, especially we had rent a car in US and driven from Chicago to San Francisco, it’s 3800 mils far, really a long trip.
1. Inner Mongolia at Feb.
2. Seoul at Mar.
3. Japan at Apr. I buy an iPad Pro and an apple watch series 4.
4. Maldives at Jun.
5. Hong Kong at Jun.
6. US. at Sep. to Oct. Details are [[/drive-in-the-us/][here]].
