---
title: "English Learning Notes From Culips"
date: 2019-07-08T14:33:00+08:00
tags: ["english", "learning", "culips"]
toc: true
---

Here is the [[https://www.youtube.com/watch?time_continue=2&v=uThg9MQqcyY][podcast]], I take some notes from it, it's really helpful if you try to leaning English. I recommand you that listen the podcast yourself multiple times.

* What the Mass Immersion Approach is

1. learning 3 to 6 hours a day, and listen in background when cooking, cleaning.
2. Compare yourself to yesterday, don’t try to compare yourself to other people.

* What’s more important input or output?

1. First really focus on input and understanding and save output speaking and writing for later.
2. If you want to be speaking fluently and native-like then you’re really not only wasting your time by practicing speaking early on but you’re actually potentially doing a lot of damage.
3. In more general language learning programs that have that philosophy to speak from day one is basically giving you grammar rules and vocabulary and they’re telling you to think in your native language and then these grammar and vocabulary to translate that into something that appears to be your target language.
4. So we need to do lots of input to find out what do native speakers say in the realistic situation that comes up.

* Matt’s tips

1. Repetition can be very useful, because if studying a foreign language you watch the same TV show or same podcast twice in a row or three times in a row you notice more stuff every time. It’ll give your brain a lot more chances to pick up more stuff.
2.  But when you listen it 10 times, you reach a point where you kind of have  sucked up all you can sucked up at the current level, and also repetition can be extremely boring.
3. Take a balance between repetition and keeping new stuff. When you gonna give something your full attention like try to watch a movie with no subtitle and try to really understand as much as I can, then always do something new. But then after you lost something actively kind of put it into a folder later, and when you want to do a more passive form of listening to English while you are shopping or cooking or walking then that’s a good opportunity to listen things you’ve already watched once actively.
4. Put these listened material on an immersion pod. There is full of English leaning materials and nothing else, so you can’t cheat. And also you don’t need to make a decision when you want to listen something.
5. Spent time with real English content like real books for native speakers, real websites or real YouTube videos, the slogan is by native for natives. You have to jump into the pool if you want to learn how to swim. Consuming the real English contents.
6. Use a repetition system like Anki.
7. Try to use an English to English dictionary as soon as you can. There is lot of learner’s English to English dictionary you can try.

* Shadowing

1. There is so many English accent, so adopting a parent, like a youtuber who makes videos of himself talking to the camera, and just listening to this one guy, when you need to speak, you can just like an actor and trying to basically play this role.
2. Good pronunciation replies very heavily on your listening abilities.

* Meditation
1. Just training your ability to concentrate, and know what’s going on in your mind, like a lot of times we get lost in thought and we don’t even realize that we’re getting lost in thought. 
2. A lot of times things are really boring because you’re not really attention to them, no matter what you take really pay attention to it closely you’re gonna find something interesting there, even if I just look at my hand and I look at all the little intricate lines and patterns in my hand, normally I would never notice it’s like oh wow my hands pretty intricate, anything intricate when you really examine it closely imagine if I had actual microscope how interesting it would be to look at my hand.
3. It’s easier to be gentle with yourself, and do not be hard on yourself, when you get through practicing meditation.

* 总结一下
1. 尽可能花更多的时间去学习，学 6 个小时肯定比学 3 个小时效果更好。
2. 不要和其他人比较，和过去你比较，是不是比过去进步了。
3. 一开始多听多写，不要着急说。只有能理解对方的文化你才有可能说好。一般初期都是从语法和单词教起，告诉你如何把从自己的语言拼出来目标语言表达，不理解对方文化习俗的话，很容易闹笑话，打击你的积极性。
4. 另外，多听写也是让你多用目标语言思考，遇到类似情况的时候脑袋里面第一跳出来的是目标语言的表达方式，而不是你自己会的语言，然后等你翻译。
5. 听的时候 ~重复~ 肯定是有用的，但是也会比较容易无聊。推荐的做法是当你准备好认真学习的时候，那就找那些没听过的，听过之后呢把他们放进一个只能用来听这个的 mp3 或者手机，然后等以后比如购物散步等做其他事情的时候，把这些放出来听。
6. 多看多听真实的英语世界的东西，比如书籍，电视什么的，口号是 by native for natives，想学会游泳肯定是需要跳进泳池才行的。
7. 使用一种用来重复记忆的辅助工具，他推荐 ~Anki~ 。可以把自己遇到的东西做成卡片放进去，比如把字幕的一整句加进去，把单词的释义放到卡片的背面。
8. ~跟读~ 是比较好的练习口语的方式，但是不要漫无目的的做这个事情，最好选一个具体的人来模仿，因为真实世界里面太多的口音了，无法都一次学会，跟一个具体的人会让你的目标小很多，更容易达成。
9. 跟读可以让你在遇到实际情况的时候，让你觉得自己像是在扮演那个人一样去说话。
10. ~冥想~ 可以练习你的专注能力。很多时候你觉得一些事情无聊其实是因为你不能专注，当你专注的时候，你会发现只是观察自己的手掌也会变得很有意思。冥想也可以让你在遇到一些挫折的时候更加容易走出来。
