---
title: "In the US"
date: 2025-06-17T08:30:20-07:00
tags: ["work", "US"]
toc: true
---
2025.1 举家 relocate 到了美国。到现在快半年了。记录一下这边的见闻。

** 很多东西都比较大
刚来的时候租车特意没选特别大的那种车，因为怕停车什么的不方便。结果出去几次就发现，他们这边的车位都奇大一个，甚至都不用倒车入库，直接头就可以进去，因为地方很大。他们这里驾照考试也没有要求说需要会倒车入库。我比较怀疑很多人可能根本就不会倒车入库。我开一个 suv，在路上有时候还会遇到那种高出我的车好多的车。这样的车都可以正常停车。

刚来就赶紧办了一个 Costco 的卡，咱也不知道是不是东西真的便宜，但是好像不去几次就不是本地人似的。几乎所有人都有个这个卡。在国内的时候我们办了山姆的卡，在这边也能用，但是山姆的店太少了。另外 Costco 还提供了相对比较优惠的汽油，另外再加上有返现什么的，整体算下来卡费可能也不算啥。
第一次去 Costco 买水就被吓到了。矿泉水都是一捆 40 几瓶那种的卖。其他的东西也类似，都是一捆一捆一箱一箱的这样的。不过还好买油的时候是可以按瓶子买的。所以立刻就理解为什么他们的冰箱都是巨大一个，车库里面也堆满了这些日常用品，因为就这么卖的。当然其实也还是有零售的地方的，但是算下来当然零售的会有一点贵。其实像水这样的东西也不容易过期，如果有地方存的话，没一堆放家里也并没有啥问题。

房子也很大，除了室内面积，还包括了院子。租的房子没有任何家具，需要新购买。好处是你总是可以用自己喜欢的家具，坏处就是对于新手来说不友好，买这些家具是一笔比较大的开销。

** 车
这边开车整体来说比国内舒服。但是路有时候比较复杂，Google 导航对新手很不友好，因为提醒非常少，经常会错过出口。但是好的地方是走错出口也没那么大影响，通常可以花个几分钟就绕回来。他们高速不收费出口非常多，不像国内错过一个口可能开半个小时才能到下一个口。Google Map 不像高德提醒那么多，高德在你快到出口的时候会不停的提醒你，Google 只有一两次提醒。相对来说 Apple Map 提醒会多一点。

这边人开车很少并线。尤其是那种四处并线的情况非常少。基本都是一条线开到出口就可以。比如如果你离出口还有 10 Mile 那就放心的在最内侧开就行了。到最后 1-2 Mile 并线就可以。大家车距也比较远，看你并线通常都会让，并线比较容易。这边即使对插队的车也很友好，所以这样也就比较少的剐蹭事故。我好像来这么久了一起都没有看到。这边开车讲路权，比如国内绿灯过路口需要带刹车，这边主张的是不减速，因为是绿灯，没道理减速，你突然减速可能反而导致后车追尾，因为后车没有预期你减速。

城市道路的设计感觉很好，这边很少有那种巨宽的路，顶多单向3车道。然后基本上来说，你如果是直行，一直在这三个车道的任何一个开都可以，很少会出现开到路口发现是一个转向车道。他们一般在路口路会变宽，多出来几条左转或者右转的车道，你有需要并线过去就可以。所以基本上来说，如果你在前面会是右转，那你就一直在最右边车道开就可以，这样整个开车过程中不需要来回并线，不容易出事故。

国内的高速的设计好像和上面的设计差不多，到出口的时候会变宽多出来一个出去的车道。这边高速上面的设计有点不一样，最右侧车道可能会变成 exit only 的车道。刚开始来的时候很不适应。遇到了只能出去转一圈再上来了。处理办法是，只在最后 1 Mile 的时候才走最右侧车道。这边并线比较容易，所以不要担心最后并不过去。但是即使最后 1 Mile 也有可能会提前遇到 exit only 的出口，诀窍就是多观望远处路牌，如果发现路牌上面有黄色的字，那就是有 exit only 车道，尽早处理就好。

停车位通常都很大，大部分时候停车都是可以直接车头开进去，都不用倒车入库。所以我估计很多老美也根本不会倒车入库。不过说时候人家车头入库的能力确实比咱强，很多时候我车头进去后会偏向一边，需要出去调整一下才行。人家就不用。。

** 吃
一家人出门吃饭差不多至少得人均 20 多，这还是快餐价格，如果是正餐可能会更贵。所以更多都是在家里吃了。偶尔可能会出去吃个中餐过过嘴瘾。这边会逼得每个人都变成中华小当家。

** 自然环境 & 公园 & 图书馆
自然环境确实是无敌的。没想到湾区这边居然不怎么下雨，比较干。每天早晚温差大，白天太阳下面特别晒，不过到了树荫下面可能反而会冷，尤其有风的时候，所以有时候不知道穿什么好。其他区域今年来了还没有怎么去过，前几天去 Tahoe 感觉还不错。沙滩就是马尔代夫那种感觉，基本免费，湖里面游泳划船也没人管。划船 2-3 个人那种 kayak $50，可以自己弄一个充气的，也就不用租了。

公园特别多，公园基本都有免费的 playground 给小朋友玩。小朋友们也其实没有其他地方可去，没有像国内一个商场十几层楼里面都是各种玩的地方。

小朋友们还可以去图书馆，有时候会有一些活动，都是免费参加的（估计都是税款支持的）。另外也可以看书，他们这边对图书馆建设还是可以的，图书馆多，书也多，还有中文书，不过很多都是香港那边的作者。一般都专门有小朋友的区域，各种绘本可以看，不过都是英文的。

** 人
人工成本比较高，所以凡是涉及到人工的都会比较贵。例如送餐，定一个送餐可能税小费加送餐费用都比餐的费用高了。打车也是很贵。所以有啥事情一般都是尝试自己搞定，例如打扫院子，送货。

这边因为住的都比较分散（很少有高过 5 层的住宅楼），导致很多可以基于聚集人群来拉低成本的事情变成不可能。例如国内快递一个人可以管好几个小区的送货，效率很高。这边就不可能，只能一户一户开车送，没办法说一栋楼 10 个快递一次送完。其实打车也是这个道理，这边接一个单可能得空载跑好远才行。其他的比如开餐馆，国内一个小区的人可能就可以养活一个餐馆。这边就很难有这样的，基本只能期望回头客了，也很难开到很大，毕竟很少有人愿意开车 30 分钟来吃饭吧。

这边人整体来说都比较友好，但是也不乏有那种瞧不上你的。遇上这种就需要仔细甄别，他们一般不会特别明显的表现出来，但是你能明显感受到对方的区别对待。
