---
title: "Year in Review 2020"
date: 2021-01-04T19:27:00+08:00
tags: ["2020"]
toc: true
---

2020 ends with the pandemic. WFH is the new normal. Many thanks to my company, I was staying at home for most of last year.

** Family
My daughter was born last year. Here name is Yoyo. Thanks for the WFH, that I could stay with her most of the time. Sometimes it was enjoyable to watch her grow up. Last winter, my wife and I have to go to the hospital to do regular checks every 2 or 3 days in the morning very early. It was tough for us. But anyway, Yoyo joins the family. She looks smart and adorable. I hope she will grow up soon. So we can travel over the world. I can't wait to through her into the clean water in the Maldives and see the smiling face from here.

My wife and I will be entering our 16 years marriage this year. I hope she and Yoyo will be happy every day, like what I said in the blog's subtitle.

** Works
Last year I left the BrilliantAero and joined Tubi, a small(?) company in the US. I worked in the Beijing office as SRE. It was a challenge for me that I need to learn lots of things, especially English. I think my English improved a lot during last year. I also learned a lot about AWS, Terraform, Ansible, and Infrastructure as Code.

We discuss topics on Github issues. I learned about how to review codes, how to cooperate with colleagues on Github. I'm immensely enjoying the time I work from home. No one will disturb you. You can work immersively.

** Readings
I begin to read some novels write for youth, so that I can persist in reading them.

Booklists:
- His Dark Materials: I finished the book before the last season of the TV show was released.
- The healer
- In the Middle of nowhere
- 东野圭吾：信
- 刺杀骑士团长
- 盗梦侦探 Paprika: I read this book after I watched the movie. The book has more details than the film. It's worth reading if you like the film.
- 以色列：一个国家的诞生
- Kubernetes in Action: It's a great book to learn Kubernetes for beginners.

** English Study
I have lots of practice during my work now. I finished the Anki deck [[https://ankiweb.net/shared/info/1035811674][托福词汇-词以类记(词典完美版)]] I started in 2019.

The quality of the deck for Anki is critical. After finished that deck, I haven't started a new deck yet. I think I will begin the deck for English Grammars. And I also begin to read a book about English Grammars. I found I almost forget what I have learned about Grammars in the colleges.

** TV

I have watched a lots of TV shows, list some of them(also reccommand):
- Homeland
- 13 Reasons Why
- Tales From The Loop
- Lost in Space(2018)
- Altered Carbon
- The Expanse
- Chilling Advanture of Sabrina
- His Dark Meterials
- Mandalorian
- The Boys
- Raised By Wolves
- Westworld
- The Witcher
- The Umbrella Academy
- kindom
- Alice in Borderland
- Dark
- Queens Gambit
- Devs
- Chernobyl
