---
title: "Year in Review 2021"
date: 2022-01-03T15:08:31+08:00
tags: ["2021"]
toc: true
---
2021 年结束了，照例来总结下。

**  Family
幼幼越长越大了，1 岁生日的时候带着去了一趟澳门，那是唯一一个算是出国又不需要隔离的地区。不过即使这样，我的健康码回来之后有几天显示无法展示状态。。然后联系各种部门都无法解决。后来自己好了。。

1 岁的时候算是刚会走路，在那边水里玩的还挺开心的，本来期望多带她玩几次水的，但是现在护照都不给你办了，很无奈。

小孩子长的是真的快，能感觉出来这熊孩子挺聪明，学东西还挺快，时不时有点意外的操作。

老婆已经开始焦虑幼儿园和学区房了。。。

** Work
在 Tubi 快两年了。感觉特别喜欢这样的工作环境，能给你足够的时间让你 focus 到一个项目，只要你愿意，可以往深了钻研。去年部署好 Kubernetes 环境之后，今年就是在强化各方面的理解了，对系统的内在运行机制有了更深的理解。工作中我时不时会感叹 Kubernetes 设计理念真好，可以让你很轻松的实现一个 Operator 来帮你做一些自动化的事情。迫于工作，也看了不少项目的源码，慢慢的喜欢上读代码了。通过读别人的代码，能学会很多东西，也能理解很多内在的行为逻辑，比单纯的看文档猜实现逻辑好多了。

自己也尝试写了一个简单的 Golang 程序，放到了生产环境。我是团队里面第一个写 Golang 的人，我想也给团队带来了一些困扰，毕竟也不是人人乐意 review Golang 代码。以后还是需要自己多写一些测试用例，自己来保证自己的实现可靠稳定吧，这块还需要提升下。写的多了，让我也开始喜欢强类型语言了，毕竟相对来说找 typo 有时候眼花找不到。。

** Reading
Book list:
- 下沉年代（没读完，放弃）
- Making Sense. The Glamorous Story of English Grammar(没读完, 放弃)
- 东野圭吾：11 字谜案（没读完）
- 挽救计划
- Dune（没读完）

去年读的书太少了，自己反思下应该是因为
1. 想读英文书，但是找一个符合我的阅读水平的我还能看的进去的书好难。
2. 为了强迫自己读英文书，也就不去读中文的书了。这样导致中文的书也没读几本。

去年年底我买了一个墨案 Mini 阅，手机那么大，但是轻很多。现在出门都带着，希望能多读几本书。

** English study
去年感觉除了日常工作中的英语学习外，自己没有什么有效的努力。当然因为天天需要英文聊天，还是能感觉自己的能力有一些提升的。

因为不想死板的背单词了，所以尝试找了一些英语教学的 podcast 来学习。English pod 这个节目，我听了20 多期（会重复反复听），自己做了 10 多期的 review，后面也停了。因为感觉方法还是不太对。

年底公司有人推荐上 Cambly，一起搭车报名了。目前上了几节课，还没有找到窍门。自己感觉是需要一个能纠正自己口语里面的错误的人，目前上的课只有一个事无巨细的帮我纠错。不过目前发现自己回头 review 自己的视频可能也有点用，目前还在摸索中。

目前的英语能力似乎听懂别人说的还行，自己表达有时候会卡住。

** TV
- Arcane: Season 1
- The Witcher: Season 2
- Lost in Space: Season 3
- Cowboy Bebop: Season 1
- Sex Education: Season 1
- Squid Game: Season 1
- The Naked Director: Season 2
- Shadow and Bone: Season 1
- Love, Death & Robots: Volume 2
- Sisyphus: Season 1
- Demon Slayer
- Fargo
- The Expanse
- Loki
- Upload
- What if ..
- Innocent
- Tails from the loop
- Solos
- Wanda Vision
- Mare of East town
